Iter7
andrey67895/go_diplom_first pull request #7
Opened 2024-07-16 19:53 UTC by andrey67895

2024-07-23 21:42 UTC, avhitrov requested changes
В общем и целом архитектура приложения годная. Но есть довольно большое количество комментариев, которые сводятся к:
- обработке ошибок
- graceful shutdown
- принципам разделения ответственности между слоями в DDD
- прочим мелким недочетам

Всё отмечено комментариями к коду, но отдельные комментарии касаются целой серии недочетов (например, разыменование).

2024-07-23 21:42 UTC, avhitrov commented on internal/job/OrdersStatusJob.go
> +		if *tModel.Status == "PROCESSING" || *tModel.Status == "INVALID" || *tModel.Status == "PROCESSED" {
```suggestion
		if tModel.Status == "PROCESSING" || tModel.Status == "INVALID" || tModel.Status == "PROCESSED" {
```
нет необходимости в явном разыменовании, Go делает это автоматически.

2024-07-23 21:42 UTC, avhitrov commented on internal/job/OrdersStatusJob.go
> +func OrdersStatusJob() {
```suggestion
func OrdersStatusJob(ctx context.Context, wg sync.WaitGroup) {
```
Для функции стоит предусмотреть graceful shutdown. Например, передать внутрь контекст, сгенеренный на старте приложения и `wg sync.WaitGroup`. Вместо `for range` использовать `for select`. А по выходу (или через defer) дергать wg.Done().

2024-07-23 21:42 UTC, avhitrov commented on internal/transport/Handler.go
> +	withdrawnHistory := services.GetWithdrawnBalanceAndSortByLogin(login, w)
В соответствии с принципами DDD, не стоит ResponseWriter опускать на уровень сервиса, возникает излишняя связность. По хорошему сервис должен вернуть внятную ошибку, а на этом уровне уже следует ее проанализировать и вернуть соответствующий http status.

2024-07-23 21:42 UTC, avhitrov commented on internal/transport/Handler.go
> +	services.WithdrawnBalanceByLogin(tWithdrawnBalanceModel, w)
https://t.me/bushigo/35
https://t.me/bushigo/36

2024-07-24 06:20 UTC, andrey67895 commented on internal/database/DBStorage.go
> +func InitDB(ctx context.Context) {
Исправлено

2024-07-24 06:20 UTC, andrey67895 commented on internal/database/DBStorage.go
> +	db := openDB()
Исправлено

2024-07-24 06:21 UTC, andrey67895 commented on internal/database/DBStorage.go
> +func openDB() *sql.DB {
Исправлено

2024-07-24 06:21 UTC, andrey67895 commented on internal/app/App.go
> +	database.InitDB(context.Background())
Исправлено

2024-07-24 06:21 UTC, andrey67895 commented on internal/database/DBStorage.go
> +		panic(err)
Исправлено

2024-07-24 06:27 UTC, andrey67895 commented on internal/database/DBStorage.go
> +func (db DBStorageModel) GetOrdersByNotFinalStatus() (*[]model.OrdersModel, error) {
Понял, исправлено.

2024-07-24 06:27 UTC, andrey67895 commented on internal/database/DBStorage.go
> +func (db DBStorageModel) GetOrdersByLogin(login string) (*[]model.OrdersModel, error) {
исправлено

2024-07-24 06:29 UTC, andrey67895 commented on internal/database/DBStorage.go
> +	data := make([]model.OrdersModel, 0)
исправлено

2024-07-24 06:30 UTC, andrey67895 commented on internal/database/DBStorage.go
> +	rows, err := db.DB.QueryContext(db.ctx, "SELECT * from orders where status in ('NEW', 'PROCESSING')")
исправлено

2024-07-24 08:38 UTC, andrey67895 commented on internal/job/OrdersStatusJob.go
> +func OrdersStatusJob() {
готово

2024-07-24 08:45 UTC, andrey67895 commented on internal/job/OrdersStatusJob.go
> +		if *tModel.Status == "PROCESSING" || *tModel.Status == "INVALID" || *tModel.Status == "PROCESSED" {
Не совсем понял, здесь же подтягиваем данные поля Status, вроде go сам это не делает

`type OrdersAccrualModel struct {
	OrderID *string  `json:"order"`
	Accrual *float64 `json:"accrual"`
	Status  *string  `json:"status"`
}`

2024-07-24 09:58 UTC, andrey67895 commented on internal/transport/Handler.go
> +	services.WithdrawnBalanceByLogin(tWithdrawnBalanceModel, w)
Я понимаю о чем речь, но в рамках моего кода/sql запросов это не воспроизводится. Вычесть и зачесть больше чем нужно и возможно не получится.

2024-07-24 11:09 UTC, andrey67895 commented on internal/transport/Handler.go
> +	withdrawnHistory := services.GetWithdrawnBalanceAndSortByLogin(login, w)
Исправил

2024-07-30 22:40 UTC, avhitrov commented on internal/job/OrdersStatusJob.go
> +		if *tModel.Status == "PROCESSING" || *tModel.Status == "INVALID" || *tModel.Status == "PROCESSED" {
Пардон, глаз замылился. Все верно, разыменовывание сделано верно, но в таком случае всегда стоит перестраховываться и сначала проверять `tModel.Status != nil && (все остальное)` , иначе можно нарваться на панику.

2024-07-30 22:45 UTC, avhitrov commented on internal/job/OrdersStatusJob.go
> +	//}
Не надо оставлять в системе хранения версий закомментированный код. Он и так в ней остается в прежних версиях.

2024-07-30 22:45 UTC, avhitrov commented on internal/transport/Handler.go
> +	services.WithdrawnBalanceByLogin(tWithdrawnBalanceModel, w)
Мое дело было обозначить проблему. В принципе, я могу закрыть ПР даже без ее решения. Главное - понимание, что в подобных системах от подобных корнер-кейсов необходимо защищаться.

2024-07-30 22:46 UTC, avhitrov approved these changes
Все основные придирки исправлены, есть пара комментариев, которые не помешают мне принять диплом. Мои поздравления!

2024-10-31 17:03 UTC, merged